xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://10.199.142.105:8081/xxl-job-admin
    executor:
      appname: xxl-job-executor-autoRetry
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9995

spring:
  redis:
    timeout: 6000
    host: 10.199.142.105
    password:
    port: 6363
    lettuce:
      pool:
        max-active: 1000 #连建池最大连接数
        max-idle: 10 #连建池最大空闲连接
        min-idle: 5
        max-wait: -1 #连建池最大阻塞时间
  datasource:
    url: jdbc:sqlserver://wddb15.wanda.cn; databasename=zndbgl
    username: zndbgl
    password: 90XBGGaRAwUo4RUh
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



