spring:
  redis:
    timeout: 6000
    host: 192.168.40.210
    password:
    port: 6379
    lettuce:
      pool:
        max-active: 1000 #连建池最大连接数
        max-idle: 10 #连建池最大空闲连接
        min-idle: 5
        max-wait: -1 #连建池最大阻塞时间
  datasource:
    url: jdbc:sqlserver://192.168.50.24\MSSQLSERVER16; databasename=NTS-9000
    username: ENC(RBc2OgQc7DTiUkYJLjGw/g==)
    password: ENC(Wvtr1ObC1m/iJed3Ftmdiw==)
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://192.168.20.192:8081/xxl-job-admin
    executor:
      appname: xxl-job-executor-autoRetry
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9999


